name: Connect 4 Move
description: Submit a Connect 4 move
labels:
  - connect4
body:
  - type: input
    id: column
    attributes:
      label: Column
      description: Pick a column from 1 to 7
      placeholder: "1"
    validations:
      required: true
